<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CncPrieniky3D_Rules</AssemblyName>
    <RootNamespace>CncPrieniky3D</RootNamespace>
    <Product>CncPrieniky3D Rules</Product>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <DefaultItemExcludes>$(DefaultItemExcludes);_dbg\**;_test\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="6.2.10" />
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
  </ItemGroup>

</Project>

